### ISSUE TITLE
bcdice: 対応しているゲームの一覧を出力する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#107]
対応しているゲームの一覧を出力する。

すべて出力すると100行以上の出力になってしまうため工夫が必要か。
頭文字だけで抽出するとか簡易検索機能を設けるとか？

**Comment by ochaochaocha3** [comment]
見にくいかもしれないですが、カンマ区切りで出力すれば行数を節約できるかも？

```
> .bcdice-list-games
DiceBot, AceKillerGene, Airgetlamh, Alsetto, Alshard, Alter_raise, ...
```

**Comment by ochaochaocha3** [comment]
bcdice/bcdice.org#4 によって https://bcdice.org/systems/ にゲームシステムIDが掲載されたので、ここのURLを出力するようにしてみます。

**Comment by ochaochaocha3** [comment]
簡易検索はこんな感じにしてみます。

* `.bcdice-search-name 名前`：ゲームシステム名で検索
* `.bcdice-search-id ID`：ゲームシステムIDで検索（大文字小文字無視）

**Comment by ochaochaocha3** [comment]
少しずつできてきましたが、次も追加したいです。

* ゲームシステム名で検索：絞り込み（半角/全角空白区切り）
* IRCボットとDiscordボットとで出力を変える
    * IRCボット：1行、カンマ区切り
    * Discordボット：複数行、見出しとIDを太字で強調表示

**Comment by ochaochaocha3** [comment]
#203 で実装しました。
