### ISSUE TITLE
プラグインから設定IDを取得できるようにする

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/rgrb#132]
設定IDごとにデータの保存先などを切り替えられるようにするため、プラグインから設定IDを取得できるようにしたい。

また、現在はConfigurableAdapterとConfigurableGeneratorとで設定にアクセスするときのインターフェースが統一されていないので、できればこの機会に統一したい（完全な統一は無理だが、ConfigurableAdapterでただのハッシュテーブルを使っていると、キーを間違えて指定してもエラーが生じず分かりにくいので、構造体などに変えたい）。

# 現在

### IRCボット

https://github.com/cre-ne-jp/rgrb/blob/30614f89729ccefb6bbf2f642f789d014a5646f7/lib/rgrb/exec/irc_bot.rb#L101-L104

### Discordボット

https://github.com/cre-ne-jp/rgrb/blob/30614f89729ccefb6bbf2f642f789d014a5646f7/lib/rgrb/exec/discord_bot.rb#L101-L104

## ConfigurableAdapter

```ruby
# RGRBのルートディレクトリ
config[:root_path]
# プラグイン固有の設定
config[:plugin]
```

## ConfigurableGenerator

```ruby
# RGRBのルートディレクトリ
# attr_reader :root_path
@root_path
self.root_path

# プラグインで使うデータを格納するディレクトリ
# attr_reader :data_path
@data_path
self.data_path

# プラグイン固有の設定は configure メソッドで得る
def configure(config_data)
  config_data['WriteTimeout']
end
```

# 変更案

## アダプタ用の設定の構造体を作る

```ruby
module RGRB
  module Plugin
    # アダプタ用の設定の構造体
    AdapterOptions = Struct.new(:root_path, :config_id, :plugin)
  end
end
```

## ボット起動時の設定

Configクラスに `attr_reader :id` を追加しておく。

```ruby
plugin_options[adapter] = Plugin::AdapterOptions.new(
  root_path, config.id,  plugin_config
)
```

## ConfigurableAdapter

```ruby
# RGRBのルートディレクトリ
config.root_path
# 設定ID
config.config_id
# プラグイン固有の設定
config.plugin
```

## ConfigurableGenerator

```ruby
# RGRBのルートディレクトリ
# attr_reader :root_path
@root_path
self.root_path

# プラグインで使うデータを格納するディレクトリ
# attr_reader :data_path
@data_path
self.data_path

# 設定ID
# attr_reader :config_id
@config_id
self.config_id

# プラグイン固有の設定は configure メソッドで得る
def configure(config_data)
  config_data['WriteTimeout']
end
```

**Comment by koi-chan** [comment]
IRC ボットについては、PR #134 にて実装完了。
Discord ボットについては、issue #133 にて実装中。

**Comment by koi-chan** [comment]
PR #150 により、構造体を使った実装に変更した。
