### ISSUE TITLE
プラグイン構成要素別の、基底クラス的に使うモジュールを作成する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#133]
DiscordAdapter には、基底クラス的に MIX-IN するモジュール `DiscordPlugin` が存在するが、IRCアダプタと共通ジェネレータには、それぞれ単独の機能しか持たないバラバラのモジュールが多数存在する状態になっている。
アダプタやジェネレータを作るとき、必ず MIX-IN する事を前提としたモジュールをそれぞれ1つずつ作成し、どのプラグインでも使いたい共通機能の全てが使えるような状態にする。

* IRCアダプタ用のモジュール
  - ConfigurableAdapter
  - Util::Logging
  - Util::NoticeMultiLines
  - Util::NoticeOnEachChannel
  - (Cinch::Plugin)
* 共通のジェネレータ用のモジュール
  - ConfigurableGenerator
  - UseLogger

なお、現在はモジュール化されていないものの、IRC送信 (`Cinch::Message#target.send(message, true)`) とログ記録 (`Util::Logging#log_notice(m.target, message)` は、ほぼ全てのプラグインで利用されているため、これも一つのメソッドにまとめたい。

`ConfigurableAdapter` は `RGRB::DiscordPlugin` でも読み込まれているため、ファイル自体は独立させた上で、`RGRB::DiscordPlugin` 及び `RGRB::IrcPlugin` で予め MIX-IN しておく方が良いと思われる。

# (例) IRCアダプタ用の基底モジュール

現在

```ruby
require 'rgrb/plugin/configurable_adapter'
require 'rgrb/plugin/util/notice_multi_lines'
require # ...

class IrcAdapter
  include Cinch::Plugin
  include ConfigurableAdapter
  include Util::NoticeMultiLines
  # ...
end
```

以下のようにプラグインを書けるようにする。

```ruby
require 'rgrb/irc_plugin'

class IrcAdapter
  include RGRB::IrcPlugin
  # ...
end
```

**Comment by ochaochaocha3** [comment]
動いたものの最小形はこんな感じでした。

# lib/rgrb/irc_plugin.rb

```ruby
# vim: fileencoding=utf-8

require 'cinch'
require 'rgrb/plugin/util/logging'

module RGRB
  module IrcPlugin
    def self.included(by)
      # ↓デバッグ用
      # puts("#{self.class}: included by: #{by}")

      by.include(Cinch::Plugin)
      by.include(Plugin::Util::Logging)
    end
  end
end

```

# プラグインの例

lib/rgrb/plugin/hello/irc_adapter.rb：

```ruby
require 'rgrb/irc_plugin'

module RGRB
  module Plugin
    module Hello
      class IrcAdapter
        include IrcPlugin

        set(plugin_name: 'Hello')
        self.prefix = /\.hello[\s　]+/
        match(/(\w+)/, method: :hello)

        def hello(m, name)
          log_incoming(m)
          message = "Hello, #{name}!"
          m.target.send(message, true)
          log_notice(m.target, message)
        end
      end
    end
  end
end
```

**Comment by koi-chan** [comment]
branch: arrange-plugin-adapter-module にて実装中。
