### ISSUE TITLE
テストをパスさせるために、本体では無駄な行を追加した

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#145]
issue #133 実装中に、ロガーをアダプタからジェネレータに渡す処理を変更した。
その弊害として、ジェネレータのテストに失敗するようになった。

https://github.com/cre-ne-jp/rgrb/compare/arrange-plugin-adapter-module#diff-9ddbf8b3184bb7d62f5db65f72d632c8R28

テストを改良し、本体からはこの行(処理)を削除したい。

**Comment by ochaochaocha3** [comment]
関連コミット：

* 34e8f299dfc5b7371cfdb471a19233f32f74a199 ジェネレータ用の基幹モジュールを実装 
* a30d8c6bb7f224740419a73a15b465a5e82a50e7 ジェネレータのロガー関係のテストが失敗するので修正
