### ISSUE TITLE
config/rgrb.yaml: Discordの設定のキーの誤り

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/rgrb#151]
以下の2ファイルでDiscordボットの設定のキーが異なる。

https://github.com/cre-ne-jp/rgrb/blob/2c87821c27cb31534aff8679a894c17f089e60ec/config/discord.yaml#L1-L4

https://github.com/cre-ne-jp/rgrb/blob/2c87821c27cb31534aff8679a894c17f089e60ec/config/rgrb.yaml#L32-L38

正しくはdiscord.yaml内の `DiscordBot`。ただ、IRCボットとDiscordボットとで使用可能なプラグインが異なるため、1つの設定ファイルを使用して両者を動作させることは難しい。rgrb.yamlをIRC用に変え、Discordの設定を除いてしまうことも対応方法のひとつとして考えられそう。

**Comment by koi-chan** [comment]
rgrb.yaml を irc.yaml に変更し、Discord の設定を削除しようと思います。

**Comment by ochaochaocha3** [comment]
了解です。rgrb.yamlはIRCボットしかなかったときから使っている設定ファイルなので、変更するのにちょうどよい機会かもしれませんね。
