### ISSUE TITLE
Bcdice: BCDice のバージョンを出力できるようにする

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#157]
https://github.com/bcdice/BCDice/blob/master/src/configBcDice.rb#L8

本家の BCDice の configBcDice.rb 内で、バージョンを定義する変数が更新されるようになった。
.bcdice-version コマンドの応答に、コミット ID だけでなく、数字のバージョンを追加する。

**Comment by koi-chan** [comment]
当該ファイルを require すると、大量のグローバル変数が有効になり、バグを生む危険がありそうです。
テキストファイルとして解析して、バージョン番号だけ抜き出したほうがよさそうに思えるのですが、いかがでしょうか。

**Comment by koi-chan** [comment]
cgiDiceBot.rb -> bcdiceCore.rb -> configBcdice.rb というつながりで、すでに require され、グローバル変数が有効になっていました。

**Comment by ochaochaocha3** [comment]
テキストファイルとして解析することに賛成です。BCDiceはv3にならないとグローバル変数を使わないように大改造されないと思うので、今のところはその方針でいきましょう。

**Comment by ochaochaocha3** [comment]
会話の流れを追えてなくて申し訳ございませんでした。グローバル変数が有効になっていたということは、`$bcDiceVersion` を直接見ればよかったです。
