### ISSUE TITLE
UrlFetchTitle: HTTPレスポンスによる例外処理

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#22]
プラグイン UrlFetchTitle において、ある程度のHTTPレスポンスを例外としてキャッチする。

例えば、
404・500エラーなどの場合、特別なメッセージを流す。
300などの転送系のエラーの場合、転送したことを知らせるメッセージを流す。

**Comment by ochaochaocha3** [comment]
リダイレクトを検知できるようにしたいですね。

**Comment by ochaochaocha3** [comment]
Net::HTTP::Persistent がエラーを捕捉してしまっていて、本来のエラーが出なくなっているようです。Net::HTTP::Persistent::Error のエラーメッセージを解析する必要があるかも…

https://github.com/drbrain/net-http-persistent/blob/master/lib/net/http/persistent.rb#L212-L225

**Comment by ochaochaocha3** [comment]
RestClient を使ったら少し扱いやすくなりました。
