### ISSUE TITLE
コマンド応答をコンソールへ出力する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#25]
IRCへの何らかの応答をした場合、その内容を標準出力または標準エラー出力に流すようにしたい。
現在のコマンドオプションには、出力をほとんど全てなくすか、cinchから出力されるメッセージをすべて出すかの2択しかない。

**Comment by ochaochaocha3** [comment]
[Cinch::Logger](http://www.rubydoc.info/github/cinchrb/cinch/Cinch/Logger) を `bot.loggers` に追加して、プラグインのログ出力を担当させるのが良いでしょうか。

**Comment by koi-chan** [comment]
お任せします!　(ぉぃ
上のクラス、結構きめ細かいログ処理ができそうですね。

**Comment by ochaochaocha3** [comment]
Logger を追加しなくても細かく制御できそうでした。

`--debug` で起動したときのログレベルが `:debug`、以前オプションなしで起動したときは `:warn` だったので、プラグイン用に間の `:info` を使えば、3 段階に分けられそうです。

コマンドラインオプションか設定ファイルで指定できるようにしたいと思います。

**Comment by ochaochaocha3** [comment]
各プラグインでよく似たログ出力処理が出てきたので、これを部品化したいと思います。`RGRB::Plugin::Logging` モジュールを作る予定です。

**Comment by ochaochaocha3** [comment]
`RGRB::Plugin::Util::Logging` という名前に変更しました。作ってます。
