### ISSUE TITLE
ServerConnectionReport: ほかのデーモンへの対応

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#27]
プラグイン ServerConnectionReport は、ngIRCd の仕様に依存している。
他のデーモンに移行すると、 &SERVER チャンネルでログが流されなくなるので、プラグインが動作しなくなる。
それぞれに依存するコードを用意しなければならないかもしれないが、少なくともCREで使うデーモンには対応できるよう、対策しなければならない。

**Comment by ochaochaocha3** [comment]
edb0661 で少しメッセージを変更しました。

**Comment by ochaochaocha3** [comment]
鯉さん（@koi-chan）が以下をコミット。

* e441482 ServerConnectionReport: ドキュメントの更新
* 25f9484 ServerConnectionReport: Atheme-Services のサポート
* d8682a9 ServerConnectionReport: 実際にサーバーを切断・接続してのバグの洗い出し

少しドキュメントの表現を修正したらマージしたいと思います。
