### ISSUE TITLE
URL が書かれたときにタイトルを取得する

### ISSUE THREAD

**Issue by ochaochaocha3** [cre-ne-jp/rgrb#5]
[Tiarra](http://www.clovery.jp/tiarra/) にある URL が書かれたときにタイトルを取得する機能（[Auto::FetchTitle](http://www.clovery.jp/tiarra/doc/module/Auto.html#module-Auto::FetchTitle)）を改良して実装する。

* HTTPS でも取得できるようにする

**Comment by ochaochaocha3** [comment]
Mechanize を使う例：http://readysteadycode.com/howto-scrape-websites-with-ruby-and-mechanize

**Comment by koi-chan** [comment]
43cf49990da12ea3383626ce5ed9a4b57387f172
作り始めました。

今後の実装予定は上のコミットのメッセージに記述してあります。

**Comment by ochaochaocha3** [comment]
エラー処理等もう少し入れる機能があるので v0.7.0 に回します。

**Comment by koi-chan** [comment]
URLの宛先がページではなかった場合、MIMEタイプと容量を調べる機能を追加したいと思います。

**Comment by ochaochaocha3** [comment]
URLの宛先がページではないかどうかは、#title を持つかどうかで判断すればよさそうです。[Object#respond_to?](http://docs.ruby-lang.org/ja/2.2.0/class/Object.html#I_RESPOND_TO--3F) が使えます。

https://github.com/cre-ne-jp/rgrb/blob/07d7516d55b9833c98c7b4bd4c3dabb0d9a21753/lib/rgrb/plugin/url_fetch_title/generator.rb#L39

```ruby
if page.respond_to?(:title)
  @reply_prefix + page.title + @reply_suffix
else
  # #title が存在しない場合の処理
end
```

**Comment by ochaochaocha3** [comment]
ちょっと実験。以下を GET したときの結果です。

* http://www.cre.ne.jp/ （通常の HTML）
* http://www.cre.ne.jp/wp-content/themes/wsc7/img/cre_banner.jpg （画像）
* http://jbpe.tripod.com/rfcj/rfc2812.j.sjis.txt （プレーンテキスト）

```ruby
m = Mechanize.new

# GET する
cre_ne_jp = m.get('http://www.cre.ne.jp/')
banner = m.get('http://www.cre.ne.jp/wp-content/themes/wsc7/img/cre_banner.jpg')
rfc2812 = m.get('http://jbpe.tripod.com/rfcj/rfc2812.j.sjis.txt')

# メソッドが存在するかどうか
[cre_ne_jp, banner, rfc2812].map { |obj| obj.respond_to?(:title) }
# => [true, false, false]
[cre_ne_jp, banner, rfc2812].map { |obj| obj.respond_to?(:content_type) }
# => [true, false, false]

# Content-Type
cre_ne_jp.content_type
# => "text/html; charset=UTF-8"
[cre_ne_jp, banner, rfc2812].map { |obj| obj.response['Content-Type'] }
# => ["text/html; charset=UTF-8", "image/jpeg", "text/plain"]

# Content-Length
[cre_ne_jp, banner, rfc2812].map { |obj| obj.response['Content-Length'] }
# => ["4983", "4297", "33769"]
```

**Comment by ochaochaocha3** [comment]
バイトサイズを読みやすくする gem もあるみたいです。

https://github.com/martinkozak/datasizes

**Comment by ochaochaocha3** [comment]
HTTP ステータスコードの表示を以下を参考にしてつけてみたいと思います。
https://github.com/rack/rack/blob/0575eb92caae30d60a7aa38f9d14dc77b565bd36/lib/rack/utils.rb#L581-L639

**Comment by ochaochaocha3** [comment]
だいたい基本機能は実装できたので、個別に issue を立てるようにしたいと思います。
