### ISSUE TITLE
ruby230: Ruby2.3.0 に対応する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#60]
2015年12月25日にリリースされる予定の Ruby 2.3.0 に対応する。
branch: ruby230

**Comment by koi-chan** [comment]
Travis-CI によるテスト(46a6d557d06b1ef9a1d2e6449ce0193e068a9d48)では、2.3.0-preview2 にてソースコードの書き換えなしで動作することを確認した。

**Comment by koi-chan** [comment]
e640de17220092b3895e388aefe56898732beaad にて、正式リリースに伴い Travis-CI 設定ファイルを更新した。

**Comment by koi-chan** [comment]
632a614ceb8656734304cb7a3c109edd6e02f1e1, 8fb2091aa1362f828f16a9be642ed1e938de3eac にて Travis-CI 設定ファイルを修正

**Comment by ochaochaocha3** [comment]
マージしました
