### ISSUE TITLE
scr-sendmail: メール送信機能の完成

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#61]
# 今後の予定
- Atheme-Services / ngIRCd などのデーモンの出力を利用するアダプターの実装
- ドキュメント・設定ファイル例の整備
- SPECファイルの書き換え(現在はエラーが出るまま)
- ログの取得

前の issue は [v0.10](https://github.com/cre-ne-jp/rgrb/milestones/v0.10) 用とし、上記の課題はこの issue で管理する。

**Comment by ochaochaocha3** [comment]
RSpecのエラーが出る件については、#71 で扱っています。

**Comment by koi-chan** [comment]
これ、すでに完了していますよね？

**Comment by ochaochaocha3** [comment]
完成してますね。閉じちゃって大丈夫だと思います。
