### ISSUE TITLE
LogSaver: データベースアダプターが出力するログをRGRBのそれに統合する

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#67]
データベース接続に関連するログは DataMapper が出力する。
現在は debug モードのログを $stdout に出力するようにソースコードで直接指定しているが、これをRGRB本体のログモード・出力先と統合したい。

**Comment by ochaochaocha3** [comment]
Generator側で出力対象のロガーを指定できるようにするといいかもしれないですね。
方法を考えねば…

**Comment by koi-chan** [comment]
RGRB 内部的な仕様に関わるのでどうやろうか悩みあぐねております。
できれば仮に実装をしてもらえるとありがたいのですがいかがでしょう。

**Comment by ochaochaocha3** [comment]
少し進みました。実は Cinch::Plugin にログ出力メソッドが入っているので、IRC アダプタを必要なときにロガーとして使う（変な感じですが）ということができました。あとは各プラグインを少し書き換えて終わりです。
