### ISSUE TITLE
LogSaver/Keyword: キーワードの扱いをどうするか

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#68]
Keyword プラグインで検索したキーワードを、現在のログ公開システムではWordPressへの投稿時に抽出している。
しかしLogSaverプラグインによりデータベースにログを保存すると、データベースからログを読み出し、直接出力することになる。
キーワードの含まれるログを抽出するクエリはログの全文検索よりも需要が高いが、これが発生したとき全文検索を行うとパフォーマンスが落ちる可能性がある。
そのため、ログの保存時にキーワードに関しては別に取り出しておいた方がよいと思われる。

これに関して、実装すべきかそうでないか、実装するならどのような方法を採るかについて、意見を求めたい。

**Comment by koi-chan** [comment]
LogSaverプラグインのログ保存部にキーワードのコマンドがあるかを検知し、キーワード専用のテーブルを定義してそこにログ行のIDとキーワードを保存する方式が良いかと思っています。

**Comment by ochaochaocha3** [comment]
実装した方が良さそうですね。できればうまくリレーションを設定したいです。

**Comment by koi-chan** [comment]
とりあえず、上のレスに書いた部分をコミットしてみました。
処理自体は今後実装してみます。

**Comment by koi-chan** [comment]
LogSaver は RGRB から分離して開発することにしたので閉じます。
