### ISSUE TITLE
Timer: IRCサーバ再接続時にTimerも再起動させる

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#69]
IRCサーバから切断され、自動再接続される機能がcinchについている。
しかし、Timerメソッドは自動的に再開されず、Jihouプラグインなどが動作しなくなる。

IRCサーバ再接続時や、特定のコマンドの投入時に、Timerを利用するプラグインを再開させたい。

**Comment by ochaochaocha3** [comment]
これはJihouプラグインを、単に1秒に1回時刻をチェックするように改修したほうがいいかもしれませんね。現在のinitializeメソッドの中でタイマーをスタートさせる方法だと、プラグインの再読み込み（現在[Cinchには未実装](https://github.com/cinchrb/cinch/issues/15)）が起こらないとそこを通らないので確かにだめそうです。現在waitで緩和している遅延は、多少なら認めるようにします？

**Comment by koi-chan** [comment]
接続時の NumericReply を検知することで、再接続時にTimerを開始させる処理を追加してみました。
b13f2c7
プラグインの中で実装するならこの方が良いかと思ったのですがいかがでしょうか。

**Comment by ochaochaocha3** [comment]
なるほど、001 の RPL_WELCOME を検知するのは良さそうです。これにしましょう！

**Comment by ochaochaocha3** [comment]
de0ebbc でマージしました。
