### ISSUE TITLE
library-versionUP: 依存する ruby-gems の一つ、"http" のバージョンを上げる

### ISSUE THREAD

**Issue by koi-chan** [cre-ne-jp/rgrb#85]
現在、http は 0.x 系列を使用するように指定されている。
これを、より新しいバージョン (2017-03-29 時点では 2.2.1) にアップデートしたい。

**Comment by koi-chan** [comment]
とりあえず他の ruby-gems は、以下の物を更新した (9d513a2e511eb952a4a3ae786b5d3655c605f5f6)

* rake
* twitter

**Comment by koi-chan** [comment]
タイムアウトまわりの例外がうまく動かなってしまいました。
発生する例外が違う物になっているのが原因らしいです。

バージョンアップ後に発生する例外：
> #<HTTP::ConnectionError: connection error: Connection timed out>

bundle exec rake を実行した結果：
```
> 5) RGRB::Plugin::UrlFetchTitle::Generator#fetch_title タイムアウトした場合 タ イムアウトしたことを示すエラーメッセージが返る
>    Failure/Error:
>      expect(generator.fetch_title(timeout_url)).
>        to eq(format[error_message])
>
>      expected: "Fetch title: !! タイムアウト[end]"
>           got: "Fetch title: !! connection error: Connection timed out[end]"
>
>      (compared using ==)
>    # ./spec/rgrb/plugin/url_fetch_title/generator_spec.rb:353:in `block (4 levels) in <top (required)>'
```

このエラーが発生しなくなるように、 https://github.com/cre-ne-jp/rgrb/commit/09de7624dbe1e036b1891fce398166cd114ef5df#diff-88722f446cbbe51d713a2dfa5822f252R126 という修正を施しましたが、他のいくつかの処理で意図したとおりに動かないかもしれません。
お時間のあるときに、検証して頂けないでしょうか。

**Comment by koi-chan** [comment]
ただし、HTTP と Twitter のバージョンを上げたことで、古い JSON への依存がなくなり、より新しいバージョンを利用できるようになっています。
JSON まわりで Ruby2.4 系列への対応に試行錯誤していたことを考えると、もっと早い時点で今回のブランチの修正を行なうべきだったかもしれません。

**Comment by ochaochaocha3** [comment]
更新ありがとうございます。http://irc.cre.jp:6667/ を入力して試してみたところ、テストの通りに正常に動くことが確認できました。修正もこの方法で問題ないと思います。

**Comment by koi-chan** [comment]
では PR にしたいと思います。

**Comment by ochaochaocha3** [comment]
マージしました。
